version: '3.9'

networks:
  lighty-storage-databases-network:
    name: lighty-storage-databases-network
    driver: bridge

volumes:
  lighty-storage-redis-volume:
  lighty-storage-postgres-database-volume:
  lighty-storage-postgres-home-volume:

services:
  redis:
    image: redislabs/rejson:2.4.3
    container_name: lighty-storage-redis
    restart: always
    ports: ["6379:6379"]
    volumes:
      - lighty-storage-redis-volume:/data
    networks:
      - lighty-storage-databases-network

  postgres:
    image: postgres:15.2
    container_name: lighty-storage-postgres
    restart: always
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: lighty-storage
      POSTGRES_USER: lighty-storage
      POSTGRES_PASSWORD: lighty-storage
    volumes:
      - lighty-storage-postgres-database-volume:/var/lib/postgresql/data
      - lighty-storage-postgres-home-volume:/root
    networks:
      - lighty-storage-databases-network
