version: '3.9'

networks:
  lighty-storage-network:
    name: lighty-storage-network
    driver: bridge

volumes:
  lighty-storage-minio-volume:
  lighty-storage-redis-volume:
  lighty-storage-postgres-database-volume:
  lighty-storage-postgres-home-volume:

services:
  minio:
    image: bitnami/minio:2023.7.18
    container_name: lighty-storage-minio
    restart: always
    ports: [ "9330:9000", "9331:9001" ]
    environment:
      MINIO_ROOT_USER: lighty-storage
      MINIO_ROOT_PASSWORD: lighty-storage
    volumes:
      - lighty-storage-minio-volume:/data
    networks:
      - lighty-storage-network

  redis:
    image: redislabs/rejson:2.6.6
    container_name: lighty-storage-redis
    restart: always
    ports: ["9763:6379"]
    volumes:
      - lighty-storage-redis-volume:/data
    networks:
      - lighty-storage-network

  postgres:
    image: postgres:15.4
    container_name: lighty-storage-postgres
    restart: always
    ports: ["5456:5432"]
    environment:
      POSTGRES_DB: lighty-storage
      POSTGRES_USER: lighty-storage
      POSTGRES_PASSWORD: lighty-storage
    volumes:
      - lighty-storage-postgres-database-volume:/var/lib/postgresql/data
      - lighty-storage-postgres-home-volume:/root
    networks:
      - lighty-storage-network
